version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.2

workflows:

  # Publish this orb as dev version
  publish-dev-version:
    jobs:
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: h-matsuo/github-release@dev:${CIRCLE_BRANCH}
          publish-token-variable: $CIRCLECI_API_TOKEN
          validate: true
          filters:
            branches:
              ignore: master
